# Generated by Django 5.1.3 on 2024-11-28 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя докладчика')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('contact', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя, задавшего вопрос')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Ответ дан')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Meetup.speaker', verbose_name='Докладчик')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание мероприятия')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('speakers', models.ManyToManyField(related_name='events', to='Meetup.speaker', verbose_name='Докладчики')),
            ],
        ),
    ]
