# Generated by Django 3.2 on 2024-11-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='телеграм id')),
                ('tg_nick', models.CharField(blank=True, max_length=50, verbose_name='Ник в телеграм')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Имя')),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='telegram_id',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tg_id', to='Meetup.users'),
        ),
    ]
