# Generated by Django 5.1.3 on 2024-11-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0002_auto_20241129_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
