# Generated by Django 5.1.3 on 2024-11-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0005_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_speaker',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Является ли пользователь докладчиком'),
        ),
    ]
