# Generated by Django 5.1.3 on 2024-11-30 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0007_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 17, 27, 57, 123138, tzinfo=datetime.timezone.utc), verbose_name='Дата и время начала'),
        ),
    ]
