# Generated by Django 5.1.3 on 2024-11-30 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0008_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 20, 14, 50, 305861, tzinfo=datetime.timezone.utc), verbose_name='Дата и время начала'),
        ),
    ]
