# Generated by Django 5.1.3 on 2024-12-04 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0009_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 16, 47, 28, 888065, tzinfo=datetime.timezone.utc), verbose_name='Дата и время начала'),
        ),
    ]
