# Generated by Django 5.1.3 on 2024-12-04 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0010_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 17, 51, 6, 522825, tzinfo=datetime.timezone.utc), verbose_name='Дата и время начала'),
        ),
    ]
